---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s | %(levelname)s | %(message)s"

handlers:
  # console:
  #     class: utils.TqdmLoggingHandler
  #     level: DEBUG
  #     formatter: simple

  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    backupCount: 2
    encoding: utf8

root:
  level: INFO
  handlers:
    # - console
    - file_handler
